services:
  subconverter:
    image: tindy2013/subconverter:latest
    container_name: subconverter
    restart: always
    ports:
      - "25500:25500"

  subweb:
    image: stilleshan/subweb:latest
    container_name: subweb
    restart: always
    ports:
      - "18080:80"
    environment:
      SITE_NAME: "subweb"
      API_URL: "http://192.168.12.3:25500"
      SHORT_URL: "http://192.168.12.3:25500"
    volumes:
      # 只挂载单个文件，避免覆盖整个目录导致“原文件看不见”
      - ./subweb/app/public/conf/config.js:/app/public/conf/config.js:ro
